- platform: mqtt
  name: "Goldene Lampe"
  command_topic: "homie/eg_anbau_goldene_lampe/relay/on/set"
  state_topic: "homie/eg_anbau_goldene_lampe/relay/on"
  payload_on: "true"
  payload_off: "false"
  availability_topic: "homie/eg_anbau_goldene_lampe/$state"
  payload_available: "ready"
  payload_not_available: "lost"
  retain: true

- platform: mqtt
  name: "Lichterkette außen"
  state_topic: aussen-lichterkette/relay/0
  command_topic: aussen-lichterkette/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: aussen-lichterkette/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: "Lichterkette"
  state_topic: eg-anbau-lichterkette/relay/0
  command_topic: eg-anbau-lichterkette/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: eg-anbau-lichterkette/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: "RGB Dachstuhl" 
  state_topic: dg-h801/relay/0
  command_topic: dg-h801/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: dg-h801/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: dg-h801/brightness
  brightness_command_topic: dg-h801/brightness/set
  rgb_state_topic: dg-h801/rgb
  rgb_command_topic: dg-h801/rgb/set
  color_temp_command_topic: dg-h801/mired/set
#  white_value_state_topic: dg-h801/channel/3
#  white_value_command_topic: dg-h801/channel/3/set 

- platform: mqtt
  name: "RGB Wohnzimmer" 
  state_topic: eg-wohnzimmer-h801/relay/0
  command_topic: eg-wohnzimmer-h801/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: eg-wohnzimmer-h801/status
  payload_available: 1
  payload_not_available: 0
  brightness_state_topic: eg-wohnzimmer-h801/brightness
  brightness_command_topic: eg-wohnzimmer-h801/brightness/set
  rgb_state_topic: eg-wohnzimmer-h801/rgb
  rgb_command_topic: eg-wohnzimmer-h801/rgb/set
  color_temp_command_topic: eg-wohnzimmer-h801/mired/set
#  white_value_state_topic: eg-wohnzimmer-h801/channel/3
#  white_value_command_topic: eg-wohnzimmer-h801/channel/3/set

- platform: mqtt
  name: "Aquariumlicht"
  state_topic: "homie/eg_aquarium_lampe/leddy/on"
  command_topic: "homie/eg_aquarium_lampe/leddy/on/set"
  payload_on: "true"
  payload_off: "false"
  effect_state_topic: "homie/eg_aquarium_lampe/leddy/state"
  effect_command_topic: "homie/eg_aquarium_lampe/leddy/state/set"
  effect_list:
    - off
    - sunny 
    - sunnyblue
    - blue
  availability_topic: "homie/eg_aquarium_lampe/$state"
  payload_available: "ready"
  payload_not_available: "lost"

