# Auslastung des Pi
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_use_percent 
    - type: load_15m
    - type: processor_use

# Außen
- platform: mqtt
  name: "Außen Temp"
  state_topic: "homie/kg_controller/outdoor/temperature"
  unit_of_measurement: "°C"
  availability_topic: "homie/kg_controller/outdoor/status"
  payload_available: "ok"
  payload_not_available: "error"
- platform: mqtt
  name: "Außen rH" 
  state_topic: "homie/kg_controller/outdoor/humidity"
  unit_of_measurement: "%"
  availability_topic: "homie/kg_controller/outdoor/status"
  payload_available: "ok"
  payload_not_available: "error"
- platform: mqtt
  name: "Außen Luftdruck"
  state_topic: "homie/kg_controller/outdoor/pressure"
  unit_of_measurement: "hPa"
  availability_topic: "homie/kg_controller/outdoor/status"
  payload_available: "ok"
  payload_not_available: "error"

# Keller
- platform: mqtt
  name: "Keller Temp"
  state_topic: "homie/kg_controller/indoor/temperature"
  unit_of_measurement: "°C"
  availability_topic: "homie/kg_controller/indoor/status"
  payload_available: "ok"
  payload_not_available: "error"
- platform: mqtt
  name: "Keller rH"
  state_topic: "homie/kg_controller/indoor/humidity"
  unit_of_measurement: "%"
  availability_topic: "homie/kg_controller/indoor/status"
  payload_available: "ok"
  payload_not_available: "error"

# Anbau
- platform: mqtt
  name: "Anbau Temp"
  unique_id: anbau_temp
  state_topic: "homie/eg_anbau_goldene_lampe/dht22/temperature"
  unit_of_measurement: "°C"
  availability_topic: "homie/eg_anbau_goldene_lampe/dht22/status"
  payload_available: "ok"
  payload_not_available: "error"
- platform: mqtt
  name: "Anbau rH"
  unique_id: anbau_humidity
  state_topic: "homie/eg_anbau_goldene_lampe/dht22/humidity"
  unit_of_measurement: "%"
  availability_topic: "homie/eg_anbau_goldene_lampe/dht22/status"
  payload_available: "ok"
  payload_not_available: "error"

# Dachstuhl
- platform: mqtt
  name: "Dach Temp"
  unique_id: dach_temp
  state_topic: "homie/dg_dht22/dht22/temperature"
  unit_of_measurement: "°C"
  availability_topic: "homie/dg_dht22/dht22/status"
  payload_available: "ok"
  payload_not_available: "error"
- platform: mqtt
  name: "Dach rH"
  unique_id: dach_humidity
  state_topic: "homie/dg_dht22/dht22/humidity"
  unit_of_measurement: "%"
  availability_topic: "homie/dg_dht22/dht22/status"
  payload_available: "ok"
  payload_not_available: "error"

########################################
# Waschmaschine (Gosund SP1)           #
########################################

- platform: mqtt
  name: waschmaschine_current
  state_topic: eg-waschmaschine/current
  unit_of_measurement: A
 
- platform: mqtt
  name: waschmaschine_voltage
  state_topic: eg-waschmaschine/voltage
  unit_of_measurement: V
 
- platform: mqtt
  name: waschmaschine_power
  state_topic: eg-waschmaschine/power
  unit_of_measurement: W
 
- platform: mqtt
  name: waschmaschine_reactive
  state_topic: eg-waschmaschine/reactive
  unit_of_measurement: VAR
 
- platform: mqtt
  name: waschmaschine_apparent
  state_topic: eg-waschmaschine/apparent
  unit_of_measurement: VA
 
- platform: mqtt
  name: waschmaschine_factor
  state_topic: eg-waschmaschine/factor
  unit_of_measurement: '%'
 
- platform: mqtt
  name: waschmaschine_energy_delta
  state_topic: eg-waschmaschine/energy_delta
  unit_of_measurement: J
 
- platform: mqtt
  name: waschmaschine_energy
  state_topic: eg-waschmaschine/energy
  unit_of_measurement: kWh

- platform: statistics
  name: "Waschmaschine Statistik" 
  entity_id: sensor.waschmaschine_power
  max_age:
    minutes: 5

- platform: template
  sensors:
    waschmaschine_status:
      value_template: '{{ states.input_select.washing_machine_status.state}}'
      friendly_name: 'Status Waschmaschine'

################################################
## Dachstuhl lüften
################################################

- platform: template
  sensors:
    delta_temp_aussen_dach:
      friendly_name: 'Temperaturdifferenz außen - Dachstuhl'
      value_template: '{{ ((float(states.sensor.aussen_temp.state)) - (float(states.sensor.dach_temp.state))) | round(2) }}' 
      unit_of_measurement: '°C'
      icon_template: "mdi:thermometer"

################################################
## Fritzbox Up/Downstream
################################################

- platform: fritzbox_netmonitor

- platform: template
  sensors:
    fritz_netmonitor_transmission_rate_down:
      friendly_name: Transmission Rate Down
#      entity_id: sensor.fritz_netmonitor
      value_template: >
                        {{ '%.0f' | format(states.sensor.fritz_netmonitor.attributes.transmission_rate_down | float / 1024)}}
      unit_of_measurement: 'kB/s'
    fritz_netmonitor_transmission_rate_up:
      friendly_name: Transmission Rate Up
#      entity_id: sensor.fritz_netmonitor
      value_template: >
                        {{ '%.0f' | format(states.sensor.fritz_netmonitor.attributes.transmission_rate_up | float / 1024) }}
      unit_of_measurement: 'kB/s'
    fritz_netmonitor_max_byte_rate_down:
      friendly_name: Max Byte Rate Down
#      entity_id: sensor.fritz_netmonitor
      value_template: >
                        {{ '%.0f' | format(states.sensor.fritz_netmonitor.attributes.max_byte_rate_down| float / 1024)}}
      unit_of_measurement: 'kB/s'
    fritz_netmonitor_max_byte_rate_up:
      friendly_name: Max Byte Rate Up
#      entity_id: sensor.fritz_netmonitor
      value_template: >
                        {{ '%.0f' | format(states.sensor.fritz_netmonitor.attributes.max_byte_rate_up| float / 1024) }}
      unit_of_measurement: 'kB/s'


################################################
## Ventilsteuerung
################################################

- platform: mqtt
  name: "Ventil 1 Timeout"
  state_topic: "homie/kg_controller/valve1/timeout"
  availability_topic: "homie/kg_controller/$state"
  payload_available: "ready"
  payload_not_available: "lost"

- platform: mqtt
  name: "Ventil 2 Timeout"
  state_topic: "homie/kg_controller/valve2/timeout"
  availability_topic: "homie/kg_controller/$state"
  payload_available: "ready"
  payload_not_available: "lost"

- platform: mqtt
  name: "Ventil 3 Timeout"
  state_topic: "homie/kg_controller/valve3/timeout"
  availability_topic: "homie/kg_controller/$state"
  payload_available: "ready"
  payload_not_available: "lost"

- platform: mqtt
  name: "Ventil 4 Timeout"
  state_topic: "homie/kg_controller/valve4/timeout"
  availability_topic: "homie/kg_controller/$state"
  payload_available: "ready"
  payload_not_available: "lost"

################################################
## DECT Thermostate 
################################################

- platform: template
  sensors:
    anbau_gruppe_temp:
      friendly_name: "Anbau Gruppe Temp"
      unique_id: "Anbau Gruppe Temp"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('climate.anbau_gruppe', 'current_temperature')}}"
    arbeitszimmer_temp:
      friendly_name: "Arbeitszimmer Temp"
      unique_id: "Arbeitszimmer Temp"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('climate.arbeitszimmer', 'current_temperature')}}"
    dach_gruppe_temp:
      friendly_name: "Dach Gruppe Temp"
      unique_id: "Dach Gruppe Temp"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('climate.dach_gruppe', 'current_temperature')}}"
#    wohnzimmer_gruppe_temp:
#      friendly_name: "Wohnzimmer Gruppe Temp"
#      unique_id: "Wohnzimmer Gruppe Temp"
#      unit_of_measurement: '°C'
#      value_template: "{{ state_attr('climate.wohnzimmer_gruppe', 'current_temperature')}}"

    anbau_gruppe_soll:
      friendly_name: "Anbau Gruppe Soll"
      unique_id: "Anbau Gruppe Soll"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('climate.anbau_gruppe', 'temperature')}}"
    arbeitszimmer_soll:
      friendly_name: "Arbeitszimmer Soll"
      unique_id: "Arbeitszimmer Soll"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('climate.arbeitszimmer', 'temperature')}}"
    dach_gruppe_soll:
      friendly_name: "Dach Gruppe Soll"
      unique_id: "Dach Gruppe Soll"
      unit_of_measurement: '°C'
      value_template: "{{ state_attr('climate.dach_gruppe', 'temperature')}}"
#    wohnzimmer_gruppe_soll:
#      friendly_name: "Wohnzimmer Gruppe Soll"
#      unique_id: "Wohnzimmer Gruppe Soll"
#      unit_of_measurement: '°C'
#      value_template: "{{ state_attr('climate.wohnzimmer_gruppe', 'temperature')}}"

################################################
## Müllabfuhr 
################################################

- platform: waste_collection_schedule
  name: Muellabfuhr
  value_template: '{{value.types|join(", ")}}|{{value.daysTo}}|{{value.date.strftime("%d.%m.%Y")}}|{{value.date.strftime("%a")}}'
