- platform: mqtt
  name: "Schalter Waschmaschine" 
  state_topic: eg-waschmaschine/relay/0
  command_topic: eg-waschmaschine/relay/0/set
  payload_on: 1
  payload_off: 0
  availability_topic: eg-waschmaschine/status
  payload_available: 1
  payload_not_available: 0

- platform: mqtt
  name: "Ventil 1"
  state_topic: "homie/kg_controller/valve1/on"
  command_topic: "homie/kg_controller/valve1/on/set"
  payload_on: "true"
  payload_off: "false"
  availability_topic: "homie/kg_controller/$state"
  payload_available: "ready"
  payload_not_available: "lost"

- platform: mqtt
  name: "Ventil 2"
  state_topic: "homie/kg_controller/valve2/on"
  command_topic: "homie/kg_controller/valve2/on/set"
  payload_on: "true"
  payload_off: "false"
  availability_topic: "homie/kg_controller/$state"
  payload_available: "ready"
  payload_not_available: "lost"

- platform: mqtt
  name: "Ventil 3"
  state_topic: "homie/kg_controller/valve3/on"
  command_topic: "homie/kg_controller/valve3/on/set"
  payload_on: "true"
  payload_off: "false"
  availability_topic: "homie/kg_controller/$state"
  payload_available: "ready"
  payload_not_available: "lost"

- platform: mqtt
  name: "Ventil 4"
  state_topic: "homie/kg_controller/valve4/on"
  command_topic: "homie/kg_controller/valve4/on/set"
  payload_on: "true"
  payload_off: "false"
  availability_topic: "homie/kg_controller/$state"
  payload_available: "ready"
  payload_not_available: "lost"

